regions:
  - global
  - eu-west-2

blocklist:
- "999999999999" # dummy value

resource-types:
  excludes:
    - S3Object # Excluded because S3 bucket removal handles removing all S3Objects
    - ServiceCatalogTagOption # Excluded due to https://github.com/rebuy-de/aws-nuke/issues/515
    - ServiceCatalogTagOptionPortfolioAttachment # Excluded due to https://github.com/rebuy-de/aws-nuke/issues/515
    - FMSNotificationChannel # Excluded because it's not available
    - FMSPolicy # Excluded because it's not available
    - MachineLearningMLModel # Excluded due to ML being unavailable
    - MachineLearningDataSource # Excluded due to ML being unavailable
    - MachineLearningBranchPrediction # Excluded due to ML being unavailable
    - MachineLearningEvaluation # Excluded due to ML being unavailable
    - RoboMakerDeploymentJob # Deprecated Service
    - RoboMakerFleet # Deprecated Service
    - RoboMakerRobot # Deprecated Service
    - RoboMakerSimulationJob
    - RoboMakerRobotApplication
    - RoboMakerSimulationApplication
    - OpsWorksApp # Deprecated service
    - OpsWorksInstance # Deprecated service
    - OpsWorksLayer # Deprecated service
    - OpsWorksUserProfile # Deprecated service
    - OpsWorksCMBackup # Deprecated service
    - OpsWorksCMServer # Deprecated service
    - OpsWorksCMServerState # Deprecated service
    - CodeStarProject # Deprecated service
    - CodeStarConnection # Deprecated service
    - CodeStarNotification # Deprecated service
    - Cloud9Environment # Deprecated service
    - CloudSearchDomain # Deprecated service
    - RedshiftServerlessSnapshot # Deprecated service
    - RedshiftServerlessNamespace # Deprecated service
    - RedshiftServerlessWorkgroup # Deprecated service

    - S3AccessPoint
    - CloudFrontResponseHeadersPolicy
    - OSPackage
    # - IAMVirtualMFADevice
    # - IAMUserMFADevice

presets:
  organization:
    filters:
      IAMSAMLProvider:
        - property: ARN
          type: contains
          value: "AWSSSO"
      IAMRole:
        - property: Name
          type: contains
          value: "OrganizationAccountAccessRole"
      IAMRolePolicyAttachment:
        - property: RoleName
          value: "OrganizationAccountAccessRole"

  defaults:
    filters:
      EC2Subnet:
        - property: DefaultVPC
          value: "true"
      EC2DefaultSecurityGroupRule:
        - property: DefaultVPC
          value: "true"
      EC2DHCPOption:
        - property: DefaultVPC
          value: "true"
      EC2VPC:
        - property: IsDefault
          value: "true"
      EC2InternetGateway:
        - property: DefaultVPC
          value: "true"
      EC2InternetGatewayAttachment:
        - property: DefaultVPC
          value: "true"

accounts:
  "535334073273":
    presets:
       - organization
       - defaults
    filters:
      IAMGroup:
        - "Admins"
      IAMUser:
        - "ming"
      IAMLoginProfile:
        - "ming"
      IAMUserPolicyAttachment:
        - "ming -> AdministratorAccess"
        - "ming -> IAMUserChangePassword"
      IAMUserAccessKey:
        - "ming -> AKIAXZJDFWO425VAH5XP"
      IAMUserGroupAttachment:
        - "ming -> Admins"
      IAMGroupPolicyAttachment:
        - "Admins -> AdministratorAccess"
      IAMRole:
        - AWSServiceRoleForAwsUserNotifications
        - AWSServiceRoleForSupport
        - AWSServiceRoleForTrustedAdvisor 
      IAMRolePolicyAttachment:
       - "AWSServiceRoleForSupport -> AWSSupportServiceRolePolicy"
       - "AWSServiceRoleForTrustedAdvisor -> AWSTrustedAdvisorServiceRolePolicy"